name: Package

on:
  workflow_dispatch:
    inputs:
      revision:
        type: string
        required: true
        description: Revision Number

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set Up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Maven Settings
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-maven-

      - name: Publish with Maven
        run: mvn deploy -Drevision=${{inputs.revision}}
