name: Package

on:
  workflow_dispatch:
    inputs:
      revision:
        type: string
        required: true
        description: Revision Number

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set Up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'oracle'
          server-id: 'github'
          server-username: ${{github.actor}}
          server-password: ${{secrets.GITHUB_TOKEN}}

      - name: Publish with Maven
        run: mvn deploy
